apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aceest-ingress
  namespace: aceest-fitness
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: aceest.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aceest-service
                port:
                  number: 80
