apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aceest-data-pvc
  namespace: aceest-fitness
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
